"""Stable fictional company directory and knowledge content for the demo tenant."""

DEPARTMENTS = [
    {"department_id": "finance", "name": "Finance", "manager": "Meera Iyer", "description": "Payments, expenses, and financial controls."},
    {"department_id": "hr", "name": "Human Resources", "manager": "Nisha Kapoor", "description": "People operations, onboarding, leave, and training."},
    {"department_id": "it", "name": "Information Technology", "manager": "Dev Malhotra", "description": "Identity, equipment, software, and service desk."},
    {"department_id": "support", "name": "Customer Support", "manager": "Arjun Menon", "description": "Customer payment issues and complaints."},
    {"department_id": "analytics", "name": "Analytics", "manager": "Ishita Rao", "description": "Business reporting and operating metrics."},
    {"department_id": "sales", "name": "Sales", "manager": "Kabir Sethi", "description": "Lead research, qualification, and follow-up."},
    {"department_id": "marketing", "name": "Marketing", "manager": "Tara Shah", "description": "Campaign planning and performance."},
    {"department_id": "operations", "name": "Operations", "manager": "Rajesh Mehra", "description": "Cross-functional process and task management."},
]

CUSTOMERS = [
    ("cust-ayush", "Ayush", "ayush@zerotouch.demo"),
    ("cust-vansh", "Vansh", "vansh@zerotouch.demo"),
    ("cust-priya", "Priya Shah", "priya@zerotouch.demo"),
    ("cust-rahul", "Rahul Patil", "rahul@zerotouch.demo"),
    ("cust-kunal", "Kunal Verma", "kunal.verma@zerotouch.demo"),
    ("cust-pooja", "Pooja Nair", "pooja.nair@zerotouch.demo"),
    ("cust-vikram", "Vikram Roy", "vikram.roy@zerotouch.demo"),
    ("cust-ananya", "Ananya Iyer", "ananya.iyer@zerotouch.demo"),
    ("cust-neha", "Neha Patel", "neha.patel@zerotouch.demo"),
    ("cust-rohan", "Rohan Joshi", "rohan.joshi@zerotouch.demo"),
    ("cust-sana", "Sana Khan", "sana.khan@zerotouch.demo"),
    ("cust-amit", "Amit Kulkarni", "amit.kulkarni@zerotouch.demo"),
    ("cust-simran", "Simran Kaur", "simran.kaur@zerotouch.demo"),
    ("cust-dev", "Dev Shah", "dev.shah@zerotouch.demo"),
    ("cust-meera", "Meera Das", "meera.das@zerotouch.demo"),
    ("cust-karan", "Karan Bhat", "karan.bhat@zerotouch.demo"),
    ("cust-lakshmi", "Lakshmi Rao", "lakshmi.rao@zerotouch.demo"),
    ("cust-isha", "Isha Menon", "isha.menon@zerotouch.demo"),
    ("cust-rahul-s", "Rahul Sharma", "rahul.sharma.customer@zerotouch.demo"),
    ("cust-arjun", "Arjun Nair", "arjun.nair@zerotouch.demo"),
    ("cust-tanya", "Tanya Bose", "tanya.bose@zerotouch.demo"),
    ("cust-farhan", "Farhan Ali", "farhan.ali@zerotouch.demo"),
    ("cust-kavya", "Kavya Reddy", "kavya.reddy@zerotouch.demo"),
    ("cust-nikhil", "Nikhil Jain", "nikhil.jain@zerotouch.demo"),
]

EMPLOYEE_NAMES = [
    ("emp-aarav", "Aarav Sharma", "aarav.sharma@zerotouch.demo", "support"),
    ("emp-meera", "Meera Iyer", "meera.iyer@zerotouch.demo", "finance"),
    ("emp-nisha", "Nisha Kapoor", "nisha.kapoor@zerotouch.demo", "hr"),
    ("emp-dev", "Dev Malhotra", "dev.malhotra@zerotouch.demo", "it"),
    ("emp-ishita", "Ishita Rao", "ishita.rao@zerotouch.demo", "analytics"),
    ("emp-kabir", "Kabir Sethi", "kabir.sethi@zerotouch.demo", "sales"),
    ("emp-tara", "Tara Shah", "tara.shah@zerotouch.demo", "marketing"),
    ("emp-rajesh", "Rajesh Mehra", "rajesh.mehra@zerotouch.demo", "operations"),
    ("emp-hr", "Kavita Rao", "hr@zerotouch.demo", "hr"),
    ("emp-neha", "Neha Patel", "neha.patel.employee@zerotouch.demo", "finance"),
    ("emp-rohan", "Rohan Joshi", "rohan.joshi.employee@zerotouch.demo", "it"),
    ("emp-priya", "Priya Nair", "priya.nair@zerotouch.demo", "support"),
    ("emp-aman", "Aman Gupta", "aman.gupta@zerotouch.demo", "finance"),
    ("emp-sana", "Sana Khan", "sana.khan.employee@zerotouch.demo", "hr"),
    ("emp-rahul", "Rahul Sharma", "rahul.sharma@zerotouch.demo", "finance"),
    ("emp-ananya", "Ananya Roy", "ananya.roy@zerotouch.demo", "it"),
    ("emp-vikram", "Vikram Malhotra", "vikram.malhotra@zerotouch.demo", "it"),
    ("emp-simran", "Simran Kaur", "simran.kaur.employee@zerotouch.demo", "sales"),
    ("emp-isha", "Isha Menon", "isha.menon.employee@zerotouch.demo", "marketing"),
    ("emp-karan", "Karan Bhat", "karan.bhat.employee@zerotouch.demo", "operations"),
    ("emp-lakshmi", "Lakshmi Rao", "lakshmi.rao.employee@zerotouch.demo", "analytics"),
    ("emp-arjun", "Arjun Nair", "arjun.nair.employee@zerotouch.demo", "support"),
    ("emp-tanya", "Tanya Bose", "tanya.bose.employee@zerotouch.demo", "finance"),
    ("emp-farhan", "Farhan Ali", "farhan.ali.employee@zerotouch.demo", "operations"),
]

TRAINING_MODULES = [
    ("TR-HR-01", "Company onboarding essentials", "hr", "People, benefits, and company ways of working."),
    ("TR-HR-02", "Privacy and information handling", "hr", "Safe handling of customer and employee information."),
    ("TR-FIN-01", "Payment operations foundations", "finance", "Payment lifecycle, settlement, and reconciliation."),
    ("TR-FIN-02", "Expense and reimbursement policy", "finance", "Expense evidence, limits, and approvals."),
    ("TR-IT-01", "Secure access basics", "it", "Identity, MFA, device security, and access requests."),
    ("TR-IT-02", "Incident reporting", "it", "How to report a security or service incident."),
    ("TR-SUP-01", "Customer care standards", "support", "Clear, empathetic customer communications."),
    ("TR-SUP-02", "Payment issue triage", "support", "Payment evidence and safe escalation."),
    ("TR-OPS-01", "Audit-ready operations", "operations", "Task ownership, verification, and audit trail."),
    ("TR-AN-01", "Data literacy and reporting", "analytics", "Interpreting operational reports responsibly."),
    ("TR-SALES-01", "Responsible customer outreach", "sales", "Permission-based lead follow-up."),
    ("TR-MKT-01", "Brand and campaign standards", "marketing", "Approved content and campaign review."),
]

KNOWLEDGE_DOCUMENTS = [
    ("KB-REFUND-01", "Refund and reversal policy", "finance", "Eligible failed UPI payments may be reversed after ledger verification. High-value, suspicious, or ambiguous payments require a human review. Refund status is visible by refund ID."),
    ("KB-EXPENSE-01", "Travel expense policy", "finance", "Travel expenses require a receipt, business purpose, travel dates, and cost center. Claims up to ₹5,000 may be auto-reviewed when documentation is complete; higher claims require a manager."),
    ("KB-LEAVE-01", "Leave and attendance policy", "hr", "Employees receive 20 annual leave days in this demo. Leave balances include approved requests only. Submit leave requests at least three working days before planned absence."),
    ("KB-ONBOARD-01", "Employee onboarding checklist", "hr", "Onboarding coordinates HR profile, department training, secure IT access, company policy reading, and manager notification. Access is requested with least privilege and is not granted automatically."),
    ("KB-IT-ACCESS-01", "Access request policy", "it", "Access requests must state the system, business reason, manager, and least-privilege level. Production and privileged access always require human approval."),
    ("KB-IT-INCIDENT-01", "IT incident response", "it", "Report security incidents immediately. Include affected system, approximate time, impact, and contact details. Do not paste secrets or credentials into tickets."),
    ("KB-SUPPORT-01", "Customer support escalation", "support", "Resolve routine payment questions from verified transaction records. Escalate explicit human requests, high risk, policy exceptions, repeated failures, and service outages."),
    ("KB-PRIVACY-01", "Customer data handling", "operations", "Use customer data only for the signed-in customer request. Do not expose internal risk scores, credentials, or data belonging to other customers."),
    ("KB-SALES-01", "Sales outreach guidelines", "sales", "Follow up only with consented business contacts. Keep messages accurate, relevant, and easy to opt out of."),
    ("KB-MARKETING-01", "Campaign review checklist", "marketing", "Campaigns need a defined audience, objective, approved copy, measurement plan, and privacy review before launch."),
]
