"""
Seeded Data and Tasks for ZeroTouch Workforce
Contains pre-worked tasks across Support, Finance, IT, and HR,
role definitions, capacity model parameters, and Academy replay scenarios.
"""

from typing import Dict, Any, List
from copy import deepcopy

# ── 1. Seeded Users & Roles ───────────────────────────────────────────────────

SEEDED_ROLES = [
    {
        "role_id": "support_agent",
        "name": "Aarav Sharma",
        "title": "Senior Support Specialist",
        "avatar": "👨‍💼",
        "domain": "support",
        "landing_page": "inbox",
        "allowed_domains": ["support"],
        "description": "Reviews pre-worked payment exceptions, approves drafted resolutions, commands SLA chases.",
    },
    {
        "role_id": "finance_analyst",
        "name": "Neha Patel",
        "title": "Lead Reconciliation Analyst",
        "avatar": "📊",
        "domain": "finance",
        "landing_page": "finance",
        "allowed_domains": ["finance"],
        "description": "Reviews automated bank statement matching, fee/GST variances, and duplicate payment flags.",
    },
    {
        "role_id": "recruiter",
        "name": "Priya Nair",
        "title": "Technical Talent Partner",
        "avatar": "🎯",
        "domain": "hr",
        "landing_page": "inbox",
        "allowed_domains": ["hr"],
        "description": "Evaluates explainable rubric scores, approves interview kits, handles scheduling conflicts.",
    },
    {
        "role_id": "skill_owner",
        "name": "Vikram Malhotra",
        "title": "Staff Operations Engineer (Skill Owner)",
        "avatar": "🛠️",
        "domain": "it",
        "landing_page": "studio",
        "allowed_domains": ["support", "finance", "it", "hr"],
        "description": "Teaches new skills via demonstration, reviews generated specs, backtests, and publishes to L1.",
    },
    {
        "role_id": "new_joiner",
        "name": "Kavita Rao",
        "title": "Associate Operations Trainee",
        "avatar": "🎓",
        "domain": "support",
        "landing_page": "academy",
        "allowed_domains": ["support"],
        "description": "Replays anonymized complex cases in sandbox, learns from AI coach feedback, tracks competency map.",
    },
    {
        "role_id": "manager",
        "name": "Rajesh Mehra",
        "title": "VP of Operations (Executive)",
        "avatar": "📈",
        "domain": "all",
        "landing_page": "dashboard",
        "allowed_domains": ["support", "finance", "it", "hr", "all"],
        "description": "Tracks freed FTE capacity, per-skill trust ladder, audit logs, and controls global emergency kill switch.",
    },
]

# ── 2. Pre-Worked Task Inbox Items ────────────────────────────────────────────

ORIGINAL_WORKFORCE_CASES: List[Dict[str, Any]] = [
    # ── Support Pack (Pack A) ──────────────────────────────────────────────────
    {
        "case_id": "CASE-SPT-9281",
        "skill_id": "upi_stuck_reversal",
        "domain": "support",
        "title": "Stuck UPI Payment — Debit without Credit",
        "priority": "HIGH",
        "status": "PREPARED",
        "autonomy_level": "L1",
        "amount": 2500.0,
        "customer_name": "Aarav Sharma",
        "customer_id": "cust-ayush",
        "evidence": {
            "transaction_id": "TX9281",
            "bank_debit": "DEBITED (Confirmed)",
            "network_switch": "SUCCESS (NPCI Ref #928104)",
            "merchant_credit": "NOT_CREDITED (Paytm Merchant Ledger)",
            "settlement_account": "NOT_FOUND (Nodal Ledger)",
            "cibil_score": 785,
            "risk_score": 0.08,
            "is_first_time": False,
        },
        "draft_action": {
            "action_type": "AUTO_REVERSAL_EXECUTE",
            "action_ref": "REV-TX9281",
            "payout_channel": "ORIGINAL_PAYMENT_SOURCE",
            "amount": 2500.0,
            "customer_message": "We confirmed your ₹2,500 payment failed to reach the merchant. Auto-reversal has been triggered back to your bank account with ETA within T+1 banking hours.",
            "tat_clock": "Active (T+0, 4h elapsed)",
        },
        "policy_cited": "RULE_W1_AUTO_REVERSAL_01: Prime CIBIL (785) & low risk (0.08) qualifies for instant autonomous reversal.",
        "assigned_role": "Support Agent",
        "approver": None,
        "outcome": None,
        "created_at": "2026-10-03T05:30:00Z",
    },
    {
        "case_id": "CASE-SPT-202",
        "skill_id": "refund_sla_chase",
        "domain": "support",
        "title": "Overdue Refund SLA Breach (> 5 Days)",
        "priority": "HIGH",
        "status": "PREPARED",
        "autonomy_level": "L1",
        "amount": 1800.0,
        "customer_name": "Rohan Mehra",
        "customer_id": "cust-rohan",
        "evidence": {
            "transaction_id": "RF202",
            "refund_acknowledged": "YES (Bank Ref #RF-991)",
            "sla_window": "5 Days (Breached by 36 hours)",
            "merchant_status": "REVERSED",
            "customer_received": "NO",
        },
        "draft_action": {
            "action_type": "DISPATCH_BANK_CHASE_API",
            "action_ref": "CHASE-RF202-HDFC",
            "compensation_flagged": "₹100/day compensation clock initiated",
            "customer_message": "Your ₹1,800 refund is overdue from beneficiary bank. ZeroTouch has dispatched an automated escalation to HDFC Bank and is tracking your compensation clock.",
        },
        "policy_cited": "RULE_W2_SLA_CHASE_01: Bank escalation API triggered per Rule 2.2 after 5-day SLA breach.",
        "assigned_role": "Support Agent",
        "approver": None,
        "outcome": None,
        "created_at": "2026-10-03T05:35:00Z",
    },
    {
        "case_id": "CASE-SPT-204",
        "skill_id": "bounced_refund_wallet_credit",
        "domain": "support",
        "title": "Bounced Bank Refund — Invalid Account/Card",
        "priority": "NORMAL",
        "status": "PREPARED",
        "autonomy_level": "L1",
        "amount": 2500.0,
        "customer_name": "Pooja Verma",
        "customer_id": "cust-pooja",
        "evidence": {
            "transaction_id": "RF204",
            "bank_status": "BOUNCED_INVALID_ACCOUNT",
            "network_status": "FAILED_RETURN",
            "merchant_status": "REVERSED",
            "destination_card": "Expired (09/26)",
        },
        "draft_action": {
            "action_type": "ISSUE_WALLET_CREDIT_CONSENT",
            "action_ref": "WAL-RF204-PROMPT",
            "wallet_credit_ready": 2500.0,
            "customer_message": "Your ₹2,500 refund bounced because your destination card expired. Click below to receive instant credit to your Paytm Wallet.",
        },
        "policy_cited": "RULE_W2_WALLET_CREDIT_01: Prompt customer for instant Paytm Wallet credit to avoid prolonged bank return loop.",
        "assigned_role": "Support Agent",
        "approver": None,
        "outcome": None,
        "created_at": "2026-10-03T05:40:00Z",
    },
    {
        "case_id": "CASE-SPT-302",
        "skill_id": "settlement_fee_breakdown",
        "domain": "support",
        "title": "Merchant Settlement Shortfall (₹50k Payout)",
        "priority": "NORMAL",
        "status": "PREPARED",
        "autonomy_level": "L2",
        "amount": 50000.0,
        "customer_name": "Sharma Electronics (Merchant)",
        "customer_id": "merch-sharma",
        "evidence": {
            "transaction_id": "S302",
            "gross_amount": 50000.0,
            "net_settled": 49000.0,
            "variance": -1000.0,
            "platform_mdr_fee": 847.46,
            "gst_18_percent": 152.54,
            "risk_score": 0.02,
        },
        "draft_action": {
            "action_type": "DISPATCH_ITEMIZED_FEE_BREAKDOWN",
            "action_ref": "STMT-S302-TAX",
            "explanation": "Shortfall of ₹1,000 matches contract platform fee (₹847.46) + 18% GST (₹152.54). Itemized tax invoice generated.",
        },
        "policy_cited": "RULE_W3_FEE_BREAKDOWN_01: Variance explained by fee schedule. Pre-authorized under L2 autonomy.",
        "assigned_role": "Support Agent",
        "approver": None,
        "outcome": None,
        "created_at": "2026-10-03T05:45:00Z",
    },
    {
        "case_id": "CASE-SPT-9342",
        "skill_id": "high_value_risk_escalate",
        "domain": "support",
        "title": "High-Value Transfer (₹18,000) — Subprime CIBIL",
        "priority": "URGENT",
        "status": "PENDING_REVIEW",
        "autonomy_level": "L1",
        "amount": 18000.0,
        "customer_name": "Kunal Verma",
        "customer_id": "cust-kunal",
        "evidence": {
            "transaction_id": "TX9342",
            "amount": 18000.0,
            "risk_score": 0.72,
            "cibil_score": 590,
            "is_first_time": True,
            "network_status": "UNKNOWN",
            "guardrail_triggered": "HIGH_VALUE_THRESHOLD_EXCEEDED (> ₹15,000)",
        },
        "draft_action": {
            "action_type": "HUMAN_SUPERVISORY_ESCALATION",
            "action_ref": "CASE-ESC-9342",
            "evidence_bundle_prepared": True,
            "recommendation": "Review device fingerprint & beneficiary KYC before authorizing manual release.",
        },
        "policy_cited": "RULE_W1_HIGH_RISK_FTU_01: First-Time User + Subprime CIBIL + amount > ₹15,000 strictly requires human approval.",
        "assigned_role": "Support Agent",
        "approver": None,
        "outcome": None,
        "created_at": "2026-10-03T05:50:00Z",
    },
    {
        "case_id": "CASE-SPT-306",
        "skill_id": "compliance_kyc_hold",
        "domain": "support",
        "title": "Merchant Payout Hold (₹45,000) — KYC Expired",
        "priority": "URGENT",
        "status": "PENDING_REVIEW",
        "autonomy_level": "L1",
        "amount": 45000.0,
        "customer_name": "QuickBite Cafe (Merchant)",
        "customer_id": "merch-quickbite",
        "evidence": {
            "transaction_id": "S306",
            "amount": 45000.0,
            "settlement_status": "HELD_KYC_EXPIRED",
            "risk_score": 0.88,
            "gstin_status": "SUSPENDED",
            "guardrail_triggered": "REGULATORY_COMPLIANCE_SUBMISSIONS",
        },
        "draft_action": {
            "action_type": "ROUTE_TO_COMPLIANCE_DESK",
            "action_ref": "HOLD-KYC-306",
            "customer_message": "Your ₹45,000 payout is currently held per RBI KYC compliance guidelines. Please upload your updated GSTIN certificate.",
        },
        "policy_cited": "RULE_W3_KYC_HOLD_01: Mandatory regulatory compliance hold. Never auto-release.",
        "assigned_role": "Support Agent",
        "approver": None,
        "outcome": None,
        "created_at": "2026-10-03T05:55:00Z",
    },

    # ── HR & Hiring Pack (Pack B) ──────────────────────────────────────────────
    {
        "case_id": "CASE-HR-101",
        "skill_id": "resume_screening_rubric",
        "domain": "hr",
        "title": "Candidate Screening — Senior Backend Architect",
        "priority": "NORMAL",
        "status": "PREPARED",
        "autonomy_level": "L1",
        "amount": 0.0,
        "customer_name": "Ananya Sundaram",
        "customer_id": "cand-8812",
        "evidence": {
            "target_role": "Staff Backend Engineer (Payments)",
            "rubric_match": "85.0% match across 4 criteria",
            "fairness_guardrail": "Protected attributes (age, photo, gender) stripped before scoring",
            "experience": "7 years fintech, distributed ledgers, Python/Go",
        },
        "draft_action": {
            "action_type": "ADVANCE_TO_PANEL_INTERVIEW",
            "action_ref": "HR-ADV-8812",
            "interview_kit": "System Design: Payment Idempotency & Fault-Tolerance (Drafted)",
            "guardrail_verified": "AI never auto-rejects. Recruiter retains final sign-off.",
        },
        "policy_cited": "RULE_HR_SCREEN_01: Explainable rubric scoring. Hire/reject decisions remain 100% human.",
        "assigned_role": "Recruiter",
        "approver": None,
        "outcome": None,
        "created_at": "2026-10-03T06:00:00Z",
    },

    # ── Finance Pack (Pack C) ──────────────────────────────────────────────────
    {
        "case_id": "CASE-FIN-201",
        "skill_id": "bank_statement_match",
        "domain": "finance",
        "title": "Daily Bank Statement Reconciliation — Line STMT-902",
        "priority": "NORMAL",
        "status": "PREPARED",
        "autonomy_level": "L2",
        "amount": 49000.0,
        "customer_name": "Nodal Settlement Ledger",
        "customer_id": "fin-ledger",
        "evidence": {
            "statement_id": "STMT-902",
            "bank_credit": 49000.0,
            "ledger_credit": 50000.0,
            "variance": -1000.0,
            "variance_reason": "MDR platform fee (₹847.46) + GST 18% (₹152.54)",
            "confidence_score": 0.99,
        },
        "draft_action": {
            "action_type": "AUTO_MATCH_POST_JOURNAL",
            "action_ref": "JRNL-STMT-902",
            "reconciliation_status": "MATCHED_WITH_VARIANCE_ENTRY",
            "journal_entry": "Dr. Bank ₹49,000 | Dr. MDR Fee Expense ₹847.46 | Dr. GST Input ₹152.54 | Cr. Merchant Settlement ₹50,000",
        },
        "policy_cited": "RULE_FIN_REC_02: Auto-reconcile statement lines where variance is verified against fee schedule.",
        "assigned_role": "Finance Analyst",
        "approver": None,
        "outcome": None,
        "created_at": "2026-10-03T06:05:00Z",
    },
]

# Mutable working copy
CURRENT_WORKFORCE_CASES = deepcopy(ORIGINAL_WORKFORCE_CASES)


def reset_workforce_data():
    global CURRENT_WORKFORCE_CASES
    CURRENT_WORKFORCE_CASES = deepcopy(ORIGINAL_WORKFORCE_CASES)
